### ISSUE TITLE
Some leading/trailing special characters can't be omitted for pattern matching to take place

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1145]
### URL(s) where the issue occurs

`https://www.shush.se/`
(I forgot an actual URL I found the issue but found this for demonstration. The issue was anyway about my custom filter)

### Describe the issue

Despite special characters such as `?` or `.` don't compose a word, omitting them from a rule leads to no matching.

For the above example URL temporarily add 
```
_ads.js?$badfilter
ads
_ads
_ads.js
ads.js
```
and see if requests `shush.se/_ads.js?` are blocked. It won't be blocked; however, any of these block:
```
ads.
_ads.
! taken from Tofu filter, a popular list in JP
_ads.js$domain=~mlb.mlb.com|~huffingtonpost.jp
_ads.js?
_ads.js^
```
To eliminate a possibility that it's specific to `ads`, I also tested these on the same URL and they didn't block corresponding requests:
```
imgcache
imgcache.php
```
but these did:
```
/imgcache
/imgcache.php
imgcache.
imgcache.php?
```
So apparently leading `/` is different from `_` and the former can't be omitted if trailing special char was omitted. A question may be whether this actually matters. EasyList/EasyPrivacy usually keep trailing special characters, but I could find some exceptions e.g.
```
_adverts.js
_rebid.js
_gaTrack.js
_nedstat.js
_nielsen.js
_pixelmap.js
_quantcast.swf
cgi-bin/counter
```
though IDK if special characters are attached in corresponding requests.

### Screenshot(s)

![_ads](https://user-images.githubusercontent.com/58900598/87042067-1a13a280-c22e-11ea-9e49-d2aab520d99f.png)

### Versions

- Browser/version: Firefox 78.0.1
- uBlock Origin version: 1.27.10

### Settings

- default + mentioned custom rules

**Comment by gorhill** [comment]
Concerning the ones with underscore (`_`), this was fixed in 1.28.0, see [I wrote about this somewhere, I need to find the reference].

For cases without underscores, then it's by design, see <https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#hosts-files>:

> So in uBO, any pattern which can be wholly read as a valid hostname, will be assumed to be equivalent to a filter of the form `||example.com^`.

**Comment by Yuki2718** [comment]
@gorhill Thx, that cleared most part of the issue. One thing I'm still not convinced is that I hardly believe `ads` or `imgcache` can be a valid host name. Are there any problem to make uBO not to take a word as a host name if it is 1) a single word without period, and 2) not included in the public suffix list?

**Comment by gwarser** [comment]
> 2) not included in the public suffix list?

By PSL rules, any singe word **is** the public suffix, even when not on the list. https://publicsuffix.org/list/

**Comment by gorhill** [comment]
The [PSL algorithm](https://publicsuffix.org/list/) says:

> 2. If no rules match, the prevailing rule is "*".

So `ads` and `imgcache` can be a TLD, as per above rule.

I think trying to change a behavior that has been in place for years, since the beginning really, is a bad idea. Filters such as `ads` and `imgcache` typically do not occur in filter lists, because as per ABP filter syntax, `ads` is equivalent to `*ads*`, which would be an inefficient, untokenizable filter and filter list maintainers know to avoid that sort of filters.

If you really want to use `ads` in your custom filters, I was going to suggest you use `/\bads\b/`, since regex syntax allows you to explicitly declare word boundaries, but I found out uBO does not deal with `\b` when it tries to extract a token from a regex. I will change the code to fix this.

**Comment by Yuki2718** [comment]
> By PSL rules, any singe word **is** the public suffix, even when not on the list. https://publicsuffix.org/list/

Thanks, didn't know that.



> The [PSL algorithm](https://publicsuffix.org/list/) says:
> 
> > 1. If no rules match, the prevailing rule is "*".
> 
> So `ads` and `imgcache` can be a TLD, as per above rule.
> 
> I think trying to change a behavior that has been in place for years, since the beginning really, is a bad idea. Filters such as `ads` and `imgcache` typically do not occur in filter lists, because as per ABP filter syntax, `ads` is equivalent to `*ads*`, which would be an inefficient, untokenizable filter and filter list maintainers know to avoid that sort of filters.
> 
> If you really want to use `ads` as a anywhere-pattern in your custom filters, I was going to suggest you use `/\bads\b/`, since regex syntax allows you to explicitly declare word boundaries, but I found out uBO does not deal with `\b` when it tries to extract a token from a regex. I will change the code to fix this.

All right, I don't need such a rule but occasionally see such rules in minor (often low-quality) lists.  Good to know it happened to improve uBO.

**Comment by gwarser** [comment]
<details>
<summary>HOST files with one-word domains blocked</summary>

```

1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 974gfbjhb23hbfkyfaby
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 alsgus132
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 amparonv60
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 bet
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 dc
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 erikuc1
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 godpore2
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 htt
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 iof
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 jasminezy16
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 joanfj11
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 kb16
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 lynettemj7
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 michelenb7
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 milagrosti5
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 moatadcom
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 mosumumopo
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 nsrf
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 p27dokhp
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 p27dokhpz2n7n
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 phishing
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 phormlabscom
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 pm
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 skimresourcecom
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 smartadserver
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 statwordprescom
1495_tankmohit's AllUnifiedHosts.txt:0.0.0.0 tuan
1906_Rhys-H Hosts-List.txt:127.0.0.1 autoproxy
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 analizamos
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 ciberdelincuentes
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 descarga
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 h
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 kaufesmarktpl
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 lovevipsale
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 prepara
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 recibimos
1937_fakeinet.com Scam, Fakes and frauds of Internet URL list.txt:127.0.0.1 schuhe
2061_Cybo's Simplified Domains.txt:0.0.0.0 singlespot
2072_Sebsauvage Hosts.txt:0.0.0.0 from
2166_urlhaus-filter (hosts).txt:0.0.0.0 bahomacom
2166_urlhaus-filter (hosts).txt:0.0.0.0 cducarrefr
2166_urlhaus-filter (hosts).txt:0.0.0.0 diamondigcom
2166_urlhaus-filter (hosts).txt:0.0.0.0 easytaxvn
2166_urlhaus-filter (hosts).txt:0.0.0.0 ekimkayadropshippingcom
2166_urlhaus-filter (hosts).txt:0.0.0.0 http
2166_urlhaus-filter (hosts).txt:0.0.0.0 hurricansk
2166_urlhaus-filter (hosts).txt:0.0.0.0 maquisagdlcom
2166_urlhaus-filter (hosts).txt:0.0.0.0 prowidorcom
2166_urlhaus-filter (hosts).txt:0.0.0.0 sebazicom
2166_urlhaus-filter (hosts).txt:0.0.0.0 ttps
337_HOSTS for Adaway for Japan.txt:127.0.0.1 o
338_Japan Hosts Ultimate.txt:127.0.0.1 o
401_notracking - Hostnames.txt:0.0.0.0 from
476_jmdugan Blocklists Microsoft.txt:0.0.0.0 office
476_jmdugan Blocklists Microsoft.txt:0.0.0.0 windows
482_Energized Blu Go Protection.txt:0.0.0.0 analizamos
482_Energized Blu Go Protection.txt:0.0.0.0 ciberdelincuentes
482_Energized Blu Go Protection.txt:0.0.0.0 country
482_Energized Blu Go Protection.txt:0.0.0.0 dateresolved
482_Energized Blu Go Protection.txt:0.0.0.0 descarga
482_Energized Blu Go Protection.txt:0.0.0.0 domain
482_Energized Blu Go Protection.txt:0.0.0.0 h
482_Energized Blu Go Protection.txt:0.0.0.0 kaufesmarktpl
482_Energized Blu Go Protection.txt:0.0.0.0 lovevipsale
482_Energized Blu Go Protection.txt:0.0.0.0 passivednsreplication
482_Energized Blu Go Protection.txt:0.0.0.0 recibimos
482_Energized Blu Go Protection.txt:0.0.0.0 schuhe
482_Energized Blu Go Protection.txt:0.0.0.0 speednetwork
490_Anti-pr0n hosts.txt:0.0.0.0 archangel202.245.160.133
4_Hosts Blocking.txt:0.0.0.0 bet
4_Hosts Blocking.txt:0.0.0.0 smartadserver
602_ThaiAntiTokenSites Hosts.txt:0.0.0.0 likefanpagethai
64_Jansal's Hosts Light.txt:192.168.1.254 invalid 1.michaelwilsonmusic.com 2.refiinc.com 2.wholesalepbm.com 2.zerocostfha.com 2wnpf.tld.cc 3.bluepointmortgage.com 3.coolerpillow.com 3.photowallrental.com
65_Jansal's Hosts.txt:0.0.0.0 invalid 1.michaelwilsonmusic.com 2.refiinc.com 2.wholesalepbm.com 2.zerocostfha.com 2wnpf.tld.cc 3.bluepointmortgage.com 3.coolerpillow.com 3.photowallrental.com
669_10ZiN Host Database (Full).txt:0.0.0.0 binary
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 ad
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 as
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 az
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 be
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 bet
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 com
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 de
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 domains
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 ee
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 fr
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 gl
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 group
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 in
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 is
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 mu
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 name
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 net
693_Ultimate Hosts Blacklist (Hosts).txt:0.0.0.0 us

```

</details>
