### ISSUE TITLE
"My Filters" section of the settings is pretty bugged

### ISSUE THREAD

**Issue by Palloxin** [uBlockOrigin/uBlock-issues#2326]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

1. the text selector does what it wants only in this extension (see the video)
https://user-images.githubusercontent.com/75091899/196031329-4fb18f16-59c0-4884-bcd6-60f67d2054b8.mp4

2. it is hard to delete lines of code, i try to use the delete button of the keyboard and lines are not delete.
https://user-images.githubusercontent.com/75091899/196031206-4fd79c1c-a40d-42c3-a10c-8d5b6ba8f0c1.mp4

3. when i delete the code of some website with the keyboard the postion of the text that is currently deleted changes randomly(see video)
https://user-images.githubusercontent.com/75091899/196031077-b59abe46-ed42-4066-bae0-c682a55dd709.mp4

### A specific URL where the issue occurs.

moz-extension://a4836e20-4ce6-4223-bdb1-e66028cb4b97/dashboard.html#1p-filters.html

### Steps to Reproduce

videos in the description

### Expected behavior

normal behaviour of a "text" editor

### Actual behavior

my filters editor bugged, hard to manage the code

### uBO version

1.44.4

### Browser name and version

Firefox mobile

### Operating System and version

Android 8 Miui 8

**Comment by ghajini** [comment]
use **anysoftkeyboard**

`https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard`

**Comment by Palloxin** [comment]
@ghajini I tried it, but the themes are ugly. I used another keyboard called Florisboard, highly customizable keyboard open source, and the problems are still there

**Comment by ghajini** [comment]
Using **anysoftkeyboard**

I can reproduce your description point 1 and i guess you want to copy the filter, just click on gutter start of filter, that serves the purpose

& for your other problems try disabling **show suggestions & auto-capitalization** feature

**Comment by Palloxin** [comment]
@ghajini i forgot to say that your keyboard doesn't bug "my filters" code editor. anyway the bug is still there , and it happens with the most used keyboard on android

**Comment by krystian3w** [comment]
#2146 - but may no possible easy test without use Firefox nightly if gorhill in free time rewrote highlight.

**Comment by BlazeFTL** [comment]
[Screenshot_20231116-110311_crDroid_Home](https://github.com/uBlockOrigin/uBlock-issues/assets/139938337/31dd2845-d070-4a70-bc98-5a31c1050860)
Topbar Not Visible In FireFox If Bottom Search Bar Is Used(For Chrome Top/Bottom Doesn't Matter)

**Comment by gwarser** [comment]
@BlazeFTL ok, I can reproduce this one. Not related to toolbar position for me. I think it happens when uBO is restoring the cursor position to the bottom of a long list of filters. Does not happen for 3-4 filters, but after restoring my backup with hundreds of lines, then placing the cursor at the bottom, I was able to reproduce. I was able to fix by putting the cursor in the first line, close the tab and open again. This does not always work, probably because the cursor position is saved after a delay.

@gorhill ?

**Comment by Palloxin** [comment]
If it can help i had a similar problem on another app with the cursor position doing weird stuff and it happened only on miui
https://github.com/LNReader/lnreader/issues/654
This has been fixed and maybe it can help.

**Comment by BlazeFTL** [comment]
Yes Problems Can Increase Depending On Android Version Or Rom...https://github.com/uBlockOrigin/uBlock-issues/issues/2805 The Video Attached There Was a A11 Rom But 95% Issues Was Solved On A13 Rom

**Comment by garry-ut99** [comment]
> Palloxin: If it can help i had a similar problem on another app with the cursor position doing weird stuff and it happened only on miui

I can still reproduce in Firefox 121 & uBO 1.54 all the issues OP reported, in two different phones & different versions of Android, one with MIUI (Xiaomi Series) and the other without (Samsung Galaxy Series), which means the issue is not specific only to MIUI. 

All the issues repored here cause managing My Filters in uBO Mobile be very cumbersome.

Also I'm aware that the issues are caused by CodeMirror rather than uBO: https://github.com/uBlockOrigin/uBlock-issues/issues/1716#issuecomment-917423757 + https://github.com/uBlockOrigin/uBlock-issues/issues/2805#issuecomment-1708871920, but if the issues will be fixed in CodeMirror, uBO will need to switch to the new version of CodeMirror.

**Comment by jeromio** [comment]
I'm using Gboard on a15 w FF and the MyFilters doesn't accept any input at all. I can't type or paste. I have no filters, I just see the "1" and a highlighted blank row and typing or pasting merely stops the cursor blinking.

**Comment by BlazeFTL** [comment]
As android versions keep moving forward its almost unusable for lower android versions i guess ?
I am on Android 13 and i cant even type site url##+js😩
Look at how many times i tried
! https://github.com/user-attachments/assets/5702dc9b-dc9f-4403-9f6e-fb3d17ce3d20

**Comment by stephenhawk8054** [comment]
Did you try another keyboard?

**Comment by gorhill** [comment]
I am still on Android 9 and I can type in text and paste text. Using AnySoftkeyboard, with "Show suggestions" disabled.

**Comment by BlazeFTL** [comment]
Tried a few other keyboards issue is present more or less...
AnySoftkeyboard does work good...only if it had good ui and few gboard features...just cant use it

**Comment by stephenhawk8054** [comment]
@BlazeFTL You can try this keyboard, it has quite similar UI to gboard: https://github.com/fcitx5-android/fcitx5-android
