### ISSUE TITLE
Filter Editor Freezes

### ISSUE THREAD

**Issue by J3ekir** [uBlockOrigin/uBlock-issues#2560]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Filter editor freezes when I try to type some characters in special positions.
"[" for example, or "]". At start I thought it's because of Alt Gr key but it's not. Alt Gr + S makes ß character in my keyboard layout and I can press it.
If I type one, maybe two characters it will unfreeze and type the characters I typed but if I put lots of them it freezes.
I tried it 

### A specific URL where the issue occurs.

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html

### Steps to Reproduce

1. Open dashboard (chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html)
2. Switch to my filters page (chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html)
3. Put your cursor in CodeMirror editor in a specific place (it's not freezing on everywhere).
4. Type "the" characters.

Characters I realized (seperated with commas): [, ], /, |, ?, =, ` and many more, I'm bored refreshing.

Magical line is this `technopat.net##:is(a[data-user-id="497606"]):upward(li)`. I realized when I tried to put [ after li at the end. I can't put that characters in that spot. It actually puts but can't show. Apply changes button stays passive but If you close or refresh the tab it says the changes may not be saved.

### Expected behavior

Work fine?

### Actual behavior

Freezing.

### Configuration

If I left here alone I can't submit the issue.
In case it doesn't fill after I click, the support page info:

uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 87143
  cosmetic: 39159
  scriptlet: 17043
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64659-45, 21m
    easyprivacy: 30725-1175, 21m
    plowe-0: 3757-933, 10d.22h.9m
    ublock-abuse: 78-0, 10d.22h.9m
    ublock-badware: 5223-114, 20m
    ublock-filters: 32011-85, 20m
    ublock-privacy: 295-2, 19m
    ublock-quick-fixes: 417-6, 18m
    ublock-unbreak: 1938-41, 19m
    urlhaus-1: 6817-0, 18m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 30
  autoUpdateDelayAfterLaunch: 5
  autoUpdatePeriod: 1
supportStats: 
  allReadyAfter: 914 ms (selfie)
  maxAssetCacheWait: 102 ms

**Comment by J3ekir** [comment]
IDK if I'm gonna get a notification via e-mail if I get a response. Just in case, If you want me to write something and I don't in a day, DM u/Bekir911 on Reddit.

**Comment by gorhill** [comment]
Probably a duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2554>. See if the same issue happens with the [dev build of uBO](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).

**Comment by gwarser** [comment]
Fixed in 1.48.1b1

Duplicate of #2554

**Comment by J3ekir** [comment]
> Probably a duplicate of #2554. See if the same issue happens with the [dev build of uBO](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).

Sorry for the duplicate. I only looked for open ones.
It happens in dev build (uBlock Origin: 1.48.1b0) too. And as in #2554 it only happens with upward ([in these ones](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#cosmetic-filters)).

**Comment by gorhill** [comment]
It's not fixed in 1.48.1b0, it's fixed in 1.48.1b2. I need to fix the release notes. Eventually the Chrome Web Store will publish the newer version.

**Comment by gwarser** [comment]
I tried local build, it's fixed in 1.48.1b1

**Comment by gorhill** [comment]
I cancelled 1.48.1b1 though because scriptlets were broken, I skipped publishing 1.48.1b2, I published 1.48.1b3 this morning, should be ready tomorrow in CWS.

**Comment by gorhill** [comment]
Probably worth publishing an emergency patch for this issue for stable release.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
Bugs on the My filters tab are still present in uBO FF 1.48.3b3 and uBO Google Chrome 1.48.3b2. To repeat the problem, you need to copy and paste the code into My filters:
```
A: https://ua-cinema.com/5319-zustrich-odnoklasnikiv-2019.html
||smachnakittchen.com^$third-party
```
Next, press the enter button twice to skip the line and re-paste the code.
