### ISSUE TITLE
[UBO-Core] snfe.useLists is not a function

### ISSUE THREAD

**Issue by toxin-x** [uBlockOrigin/uBlock-issues#3402]
### Prerequisites

- [x] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when i try running the example script this is the error i get

```
Uncaught TypeError TypeError: snfe.useLists is not a function
    at <anonymous> (/home/toxin/Documents/code/git/superurl/test.js:5:12)
    at run (internal/modules/esm/module_job:262:25)
No debugger available, can not send 'variables'
Process exited with code 1

```

### A specific URL where the issue occurs.

```yaml
if ( snfe.matchRequest({
    originURL: 'https://www.bloomberg.com/',
    url: 'https://www.bloomberg.com/tophat/assets/v2.6.1/that.css',
    type: 'stylesheet'
}) !== 0 ) {
    console.log(snfe.toLogData());
}
```

### Steps to Reproduce

1. install UBO-core, the offical package only has the package.json and no code so i used @softwiz/ubo-core which looks the same.
2. paste example code from readme into a file named test.js
3. run file

### Expected behavior

for the code to tell me if the site was blocked or not

### Actual behavior

```
Uncaught TypeError TypeError: snfe.useLists is not a function
    at <anonymous> (/home/toxin/Documents/code/git/superurl/test.js:5:12)
    at run (internal/modules/esm/module_job:262:25)
No debugger available, can not send 'variables'
Process exited with code 1

```

### uBO version

@softwiz/ubo-core

### Browser name and version

Node.js v22.8.0

### Operating System and version

Manjaro Linux KDE latest

**Comment by gorhill** [comment]
Does it work if you use:

    npm i @gorhill/ubo-core@0.1.25

**Comment by gorhill** [comment]
I removed 0.1.26 from NPM, I don't what happens years ago when I published it, it was a bad package. Install 0.1.25.

`useLists` is an instance method of `StaticNetFilteringEngine`. You create an instance using `StaticNetFilteringEngine.create()`. The package uses ES import/export.

**Comment by toxin-x** [comment]
sadly I am still getting the error on 0.1.25, attached is my full code along with the error log. Thank you for the assistance.

![image](https://github.com/user-attachments/assets/ce32b817-5d8c-40ad-954a-6d436e14614a)

**Comment by gorhill** [comment]
Sorry, the documentation is wrong, `StaticNetFilteringEngine.create()` is asynchronous, it returns a promise. Need:

    const snfe = await StaticNetFilteringEngine.create()

**Comment by gorhill** [comment]
Also the documentation should be:

```js
await snfe.useLists([
    fetch('easylist').then(r => r.text()).then(raw => ({ name: 'easylist', raw })),
    fetch('easyprivacy').then(r => r.text()).then(raw => ({ name: 'easyprivacy', raw })),
]);
```

**Comment by toxin-x** [comment]
thank you, that fixed this issue, i changed it from 'easylist' to the URL because when i tried using just easylist i got `Uncaught TypeError TypeError: Failed to parse URL from easylist at <anonymous> (<node_internals>/internal/deps/undici/undici:13185:13)`

**Comment by gorhill** [comment]
Did you also [apply this fix](https://github.com/uBlockOrigin/uBlock-issues/issues/3402#issuecomment-2395573349)?

I fixed the documentation and published [0.1.28](https://www.npmjs.com/package/@gorhill/ubo-core), hopefully that now will work out of the box as per documentation.

**Comment by toxin-x** [comment]
on 0.1.28 i am still getting
 `Uncaught TypeError TypeError: Failed to parse URL from easylist at <anonymous> (<node_internals>/internal/deps/undici/undici:13185:13)` 

this is my code:
```js
const { StaticNetFilteringEngine } = await import('@gorhill/ubo-core');

const snfe = await StaticNetFilteringEngine.create();

await snfe.useLists([
    fetch('easylist').then(r => r.text()).then(raw => ({ name: 'easylist', raw })),
    fetch('easyprivacy').then(r => r.text()).then(raw => ({ name: 'easyprivacy', raw })),
]);```

**Comment by gorhill** [comment]
Replace `'easylist'` with a valid URL where EasyList is hosted. I would recommend you download EasyList from official server once locally and fetch from local server to avoid fetching a list every time you want to test your code.
