### ISSUE TITLE
Some rules doesn't show up in the Legacy version's logger

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uBlock-issues#385]
### Issue:
Some rules doesn't show up in uBlock Origin's logger, when using the Legacy version.
This makes it very difficult to troubleshoot some filter issues.

### Examples:
`https://github.com/uBlockOrigin/uAssets/issues/4660/#issuecomment-455715636`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.3.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.6 (XUL)

**Comment by gorhill** [comment]
Possibly same issue as was solved in <https://github.com/gorhill/uBlock/commit/3d867baf0b844cb1d411f5dacbec3c1b95108d3c>.

**Comment by THEtomaso** [comment]
@gorhill:

Unfortunately, the fix doesn't work.

`##iframe[src*="annonse"] `still doesn't show up in the logger here:
`https://www.dagbladet.no/annonse/70179055/`

And `###cookie:not(body):not(html):not([href*="cookieclicker"])` doesn't show up here:
`https://www.acronis.com/en-us/support/contact-us/`

**Comment by gorhill** [comment]
> Unfortunately, the fix doesn't work

I will decline then. Pull requests are welcomed to fix the issue, no need to keep this one opened.

**Comment by THEtomaso** [comment]
@gorhill:
Could you please take a look at (or at least comment on), Feodor2's finding, in the post above?

**Comment by gorhill** [comment]
There is no finding, he just linked to a line with no visible effort to actually make a point of why he think this there is an issue there. When I ask for a pull request, I ask for someone to go through the efforts of understanding the code and providing a proper solution to it.

**Comment by gorhill** [comment]
I just remembered that this was fixed in uBO, see <https://github.com/uBlockOrigin/uBlock-issues/issues/102>.

**Comment by THEtomaso** [comment]
OK, is that fix directly compatible with the Legacy version, or does it require a different approach?

**Comment by gorhill** [comment]
The fix won't work with legacy, because there is no infrastructure code to inject scriptlet in specific frames in legacy -- this was one of the shortcoming of legacy holding back fixing properly many issues. Supporting injecting in specific frames through `frameId` is going to be a huge undertaking for whoever wants to take on this. The proposed fix above is an inefficient crutch _at best_, this may/will cause the logging scriptlet to be injected repeatedly in a frame (hence why the test against top window, to ensure it is injected once in any given frame).

**Comment by joey04** [comment]
FYI for legacy users:

You can use [my archived XUL fork of uBO](https://github.com/joey04/xulBlock-Advanced) as an alternative to the semi-maintained official version. It was hard-forked from 1.14.16, so it doesn't have this logger regression; the logger works perfectly. I haven't maintained it in almost a year, since I switched to Firefox, but it still should work fine.

**Comment by THEtomaso** [comment]
I'm aware of your fork, joey04.
..but unfortunately, more important fixes than the one we've been discussing here, has been added to the Legacy branch, since you last updated your version.

**Comment by Feodor2** [comment]
>this may/will cause the logging scriptlet to be injected repeatedly in a frame

In other words if affected page element is inside a frame it will log repeatedly. I tested with a simple page without frames, and that value always was false thats why i decided remove its check, turned out you made it never possible log on pages without frames why? So i shell test with more complicated page with frames.

**Comment by Feodor2** [comment]
I have tested and yes that log is repeated, so that is to be developed with frameId thing, shell try then.
