### ISSUE TITLE
Dark Mode support

### ISSUE THREAD

**Issue by BenSokol** [uBlockOrigin/uBlock-issues#401]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

macOS 10.14 introduced "dark mode", which swaps the system color palette to a dark scheme. Chrome just added support for this in Google Chrome Canary. uBlock Origin doesn't currently support this. I realize this is Canary, however Dark Mode will be added to a future version of Google Chrome. It is presently on track to be in m73 (March 12, 2019) or m74 (April 23, 2019). NOTE: This is not a Canary "Bug" it is a new feature that will be added to chrome.

### A specific URL where the issue occurs

Chromium Issue Tracker showing "Dark Mode" is now enabled by default in Chromium. As Google Chrome Canary is built off master nightly, this is present there. https://bugs.chromium.org/p/chromium/issues/detail?id=850098#c58
Release Schedule for Chromium/Chrome: https://www.chromium.org/developers/calendar

### Steps to Reproduce

1. Open Google Chrome Canary (must be updated past Thursday, January 24, 2019's nightly build. 
2. Open any of uBlock Origin's menus (i.e. click icon in menu bar, go to extension settings, etc.)

### Expected behavior:

uBlock Origin's Menu pages are bright white with black text. They should (in theory) follow Google Chrome Canary's default color scheme, which has now been expanded.

### Actual behavior:

Google Chrome Canary appears in dark mode, however uBlock Origin menus are all bright white with black text (same as normal mode)

### Your environment

* uBlock Origin version: 1.18.1rc0
* Browser Name and version: Google Chrome Canary (Version 73.0.3683.3 (Official Build) canary (64-bit))
* Operating System and version: macOS Mojave (Version 10.14.3)

**Comment by tophf** [comment]
Apparently you will be able to do it via the new CSS `@media (prefers-color-scheme: dark)` in Canary: https://crrev.com/c/1396404 is the first step, but the actual support is not yet implemented IIUC.

**Comment by colbycdev** [comment]
Would this be similar achievable in Firefox? I know FF does not normal have dark mode (ok, ok, there are themes [or substratum on Android]) but an option for a dark color scheme in the extension would be awesome.  

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by uBlock-user** [comment]
With `74.0.3716.0` on Windows 10, Chromium's dark mode is now activated if you have dark theme on OS.

**Comment by johnp** [comment]
Firefox recently received [support](https://bugzilla.mozilla.org/show_bug.cgi?id=1494034) for `prefers-color-scheme`. There already is an unofficial dark theme available under the [ShadowFox](https://github.com/overdodactyl/ShadowFox/blob/master/css/userContent-files/webextension-tweaks/ublock_origin.css) project that maybe could be used.

**Comment by dannycolin** [comment]
@johnp Firefox also has an official dark mode. Support for `prefers-color-scheme` of that dark mode is currently in Nightly (https://bugzilla.mozilla.org/show_bug.cgi?id=1519547). I guess opening an issue specific to FF would be a good idea.

**Comment by jeremyperkin** [comment]
Hi,

So I will have this completed before the end of the week.   At least that is what I expect.   Would like to get some feed back on colour scheme that I have used so far.   Any chance someone would like to copy the popup.css code that I have put here and run with it for a bit.   Please rename your copy of popup.css to popup.old and just paste the code here into your popup.css file.   https://github.com/jeremyperkin/uBlockdark/blob/master/popup.css

**Comment by jeremyperkin** [comment]
Dark Mode has been completed for chromium.  Wondering if @gorhill you have time to connect?   Here is the candidate for consideration v.01 https://github.com/jeremyperkin/uBlockdark

**Comment by gorhill** [comment]
Thanks, give me some time to look into this, this might be only in the next weekend though.

**Comment by jeremyperkin** [comment]
> Thanks, give me some time to look into this, this might be only in the next weekend though.

Hi, Just wounder if you have had a chance to take a look?
This way I can make adjustments and implement your ideas or thoughts.

**Comment by jeremyperkin** [comment]
@gorhill almost been a month since I have heard back from you.  Hope everything is ok.  But I know you are probably super busy.

Here is a link to version I was working on - just variable names that I found were throughout the code.   I am looking to do more but just waiting on the word from you.  https://github.com/jeremyperkin/uBlockdark/tree/master/variables

Interested in also working on more projects as well.

**Comment by Crystal-RainSlide** [comment]
> https://github.com/jeremyperkin/uBlockdark/tree/master/variables

Now [https://github.com/jeremyperkin/uBlockdark/blob/master/uBlock Dark Mode/varDark.css](https://github.com/jeremyperkin/uBlockdark/blob/master/uBlock%20Dark%20Mode/varDark.css)

(Semicolons missing till [this commit](https://github.com/jeremyperkin/uBlockdark/blob/5c759df5c4ce422b12363f49975c4d88f9ba5bc7/uBlock%20Dark%20Mode/varDark.css))

**Comment by jeremyperkin** [comment]
@gorhill Where do we stand with implementing dark mode?   Have you reviewed the code as of yet?  Noticed that it has almost been a couple of months since we chatted on this.

**Comment by gorhill** [comment]
@jeremyperkin,

I could not use the work you posted above since when I tried it, it removed the default theme to replace it completely with the dark theme, i.e. this was a destructive change. The default needs to be preserved and the dark theme needs to be enabled condtionally.

In any case there is now infrastructure to add a dark theme. The way to do this is to add dark theme color values in <https://github.com/gorhill/uBlock/blob/b5d8b0a9f0f7fd6e812621188634b03a0197fc60/src/css/themes/default.css#L96-L102>. The color values you add in there should override the default color values when someone enable dark theme in their browser or OS.

At this point there is more work to allow to completely support dark theme, for example I didn't yet touch the logger UI (this would have further delayed being able to start on a dark them), this will be completed in the coming days, and I will keep fine-tuning according to difficulties you may encounter while implementing the dark theme.

Since the theme infrastructure is now there, it's a matter of you filling in the color values and making a pull request to commit the changes in into uBO -- tell me when you are ready to make a pull request.

**Comment by jeremyperkin** [comment]
@gorhill 

I am ready to do a pull request.  Let me know when to give it a pull!

**Comment by gorhill** [comment]
You can create a pull request on the `dark` branch: <https://github.com/gorhill/uBlock/tree/dark>.

**Comment by jeremyperkin** [comment]
@gorhill been away due to the virus.

Back and have been looking at the new 1.27.0 variables.   I have mapped them all and we could just use the current vars that have been setup.   Would need a few more setup and attached to elements though.  

Not use to doing pull request etc with github as I only used it to ever download or upload my own repos.   So today I will pull this down.

Do you think that using the vars in place would be the best?   Or do you want full on new variables created.   Thought that it would make it easier to do the implementation since all that would be changing is the values.   Let me know your thoughts!

**Comment by gorhill** [comment]
Can you commit you changes to your <https://github.com/jeremyperkin/uBlock/commits/dark> so that I can give a look at them first?

Ideally, only the values of the CSS variables changes -- though I don't think all the need variables are in there. For example, uBO's syntax highlight colors are not present in there and this causes issues with dark theme. If you see variables missing, tell me about them, I will decide whether I add them or convert the custom colors to CodeMirror's built-in colors (which supports theming).

**Comment by jeremyperkin** [comment]
Unsure if I messed things up.  But commit has been made.

I have noted the changes that I think need to be made to fully allow things to work properly.    Since I saw that there was a background color in the media line that you added I just worked with that.

I did not locate the highlighting values as I could not find variables for them.

**Comment by jeremyperkin** [comment]
@gorhill know that you are busy - just wondering if there is feedback so that I can take care of it and adjust things if needed?

Have a wide open day today and would enjoy getting something accomplished :)

**Comment by gorhill** [comment]
I have to leave the computer soon and won't be able to provide feedback during the day. However I looked quickly at the change and I could tell it's not something I can pull into uBO as it is. There are changes not related to color scheme in there, and change not suitable to be in uBO (`-moz-`?) Also, I had the intention of following closely the material design guidelines and Photon named colors.

**Comment by jeremyperkin** [comment]
That -moz-FieldText info was taken straight from the code.   If you notice I have included each file where things are located for efficiency.

**Comment by jeremyperkin** [comment]
Revision has been posted.

Hopefully this is in step with the uBlock Origin Brand.   Feel free to offer feedback or criticism

**Comment by jeremyperkin** [comment]
@gorhill Been a few days.  Are we able to discuss this?

**Comment by gorhill** [comment]
I left a comment in your repo yesterday: <https://github.com/jeremyperkin/uBlock/commit/10596915938836a9fe11d3d14296a6b4458f16aa#commitcomment-39309751>:

> There is no need to redefine in the `:root.dark { ... }` section the named colors which are already defined at the top of the file. Feel free to add those which are missing though, from <https://protocol.mozilla.org/fundamentals/color.html>.

**Comment by jeremyperkin** [comment]
That was fixed when I changed it all and made my second commit

**Comment by gorhill** [comment]
This is not fixed:

    :root.dark {
        --light-gray-10: #f9f9fb;
        --light-gray-10-a4: #f9f9fb0a;
        --light-gray-10-a12: #f9f9fb1f;
        --light-gray-10-a16: #f9f9fb29;
    ...

**Comment by jeremyperkin** [comment]
Ok, I will remove the variables.  Have you checked what things now look like?  Are you satisfied or are there more changes that I can make.

I wanted to ask:
1. Any chance you could change the hover to use FILL on the pop-up.  This would look better than how it comes up now.

2.  Just the question of adding variables to the elements that I previously suggested.  Which would allow for the My Filters, My Rules, Whitelist and Advanced Settings windows to get a dark version.

**Comment by gorhill** [comment]
I just imported your changes and looked at the result. For now two points:

I already had a [bit of work done]https://github.com/gorhill/uBlock/blob/ce3d316d28f42847bc5ba9d1a877c8186d744bd5/src/css/themes/default.css#L204-L220), I would like these to be kept for now, I spent a good amount of time picking these according to the documentation. Currently, the contrast for the checkboxes and buttons is way too low IMO.

Do not use `!important`.

**Comment by jeremyperkin** [comment]
I understand not to use !important.  
Explanation: How I work - I just took the Default.css file into my editor - imported it in to my workflow.  Then walked through and edited it.  Verified the colours and look and then saved and wrote.  Needed !important at the time to overwrite the colours already set.   

Wonder if the problem with the contrast is that I am using my Pro Display XDR monitor.  Just checked on my Ultra Wide BenQ 35 inch and it looks alright as well.  (could be the brightness and contrast it's using though).

**Comment by gorhill** [comment]
One thing I also did when I started to create the dark mode color is that I looked at the dark mode colors of Firefox Preview in its user interface. Since the idea for the light theme was to follow Firefox Preview colors, I applied the same guideline for the dark them.

**Comment by jeremyperkin** [comment]
Ok, I will add back the 6 changes that I made - as I did take from what was already started.

One thing that you might want to consider is that Firefox Fenix is for mobile so the contrast and DPI is going to be quite different from what will be able to be displayed on computer displays.

**Comment by jeremyperkin** [comment]
Removed !important.  Changed to the OG colours you chose.

**Comment by gorhill** [comment]
Thanks. I think I am going to pull this into my `dark` branch and from there I can make some needed changes (I need to add code to pull in CodeMirror dark theme for advanced settings and asset viewer) and further tidy up the CSS variables needed (some I meant to replace with named colors, the `hlsa` ones) and once done we can keep discussing the colors. For example I think I prefer the power button to stay blue in the dark theme, it's kind of a uBO recognizable visual.

**Comment by jeremyperkin** [comment]
Alright let me know - so we can get this completed!

Hopefully what I contributed made difference!

**Comment by jeremyperkin** [comment]
Please make a cloudWidget-bg variable.   As that would love the cloud widgets not being shown.   Recommend that cloudWidget-bg: var(default-surface).  This would solve the looks of it in current dark mode.

**Comment by gorhill** [comment]
I will just remove the background image, uniform color is just fine. For today I won't have more time to work on this so I might not answer against until tomorrow.

**Comment by jeremyperkin** [comment]
All good!  On thing you can do with the codemirror.css is set .CodeMirror element background from white to var(—dark-grey-90). That will solve all the windows with the white block.

**Comment by jeremyperkin** [comment]
So I took the time to go through and complete logger-ui and worked with elements without using the cm values.   I just used the colours  we had been using for consistency.

I  can change all the files on my own with my fork if you want or can hand this off to you - I included line numbers which can become approx. due to the changes being made.  But super simple to get done.  

Let me know you either way.   But from the looks of things it is pretty complete.  Just have a few things here and there to complete.  (Got late so I stopped for a break)

**Comment by jeremyperkin** [comment]
@gorhill Morning!  Here is the config that I spoke of.  [Extra config for .css files](https://github.com/jeremyperkin/uBlockdark/blob/master/Dark%20Mode%20extra%20files.css)

Hopefully this helps out.  I have included the line numbers > which could change at times give the modifications.  But should be close.

**Comment by sharethewisdom** [comment]
Any progress on reviewing the dark branch?

I'm using dark mode in Firefox (ui.systemUsesDarkTheme=1) on Linux with uBlock Origin 1.27.7b3 and a custom userChrome/userContent created with [shadowfox](https://github.com/overdodactyl/ShadowFox/) and I'm eager to test it and to create shadowfox branch where I'd probably just get rid of the [ublock_origin.css](https://github.com/overdodactyl/ShadowFox/blob/master/css/userContent-files/webextension-tweaks/ublock_origin.css) file.

**Comment by jeremyperkin** [comment]
@sharethewisdom  Unsure what you are talking about....  since this has not been completed.  Plus it is still working on the elements it can work on currently.

@gorhill  It's been a week + any chance you reviewed the CSS elements that I provided so we can bypass the limitations of the CM and the colors the handling of colors it allows for?

**Comment by dobata** [comment]
doesn't look good either way with "Force Dark Mode for Web Contents" flag on, I understand it's a niche case, but I though it's worth mentioning

**Comment by lucknaumann** [comment]
@sharethewisdom I used to use overdodactyl/ShadowFox too, but it stopped working well and seemed it hadn't been updated for a while. Now I use Izheil/Quantum-Nox-Firefox-Dark-Full-Theme which, to me, works better and is continually updated. Just thought you might be interested.

@dobata FWIW - as I  mentioned in issue #1090, before the UI change, which also came with the color changes, the colors were fine when using the "Force Dark Mode for Web Contents" flag. I've turned that on in the Chrome(ium) browsers I use ever since it was available and never had an issue with reading the icons, including in the Dashboard > Filter lists tab. I know you didn't mention this but as additional info: using Classic UI mode via Advanced Settings > `uiFlavor ` > `classic ` doesn't change the colors back.

**Comment by happysurf** [comment]
Firefox 82 beta6 + UBO 1.30.1b2 + W10 in dark mode.
This is the result:

![Dark ubo](https://user-images.githubusercontent.com/13637587/94988141-6e979700-056b-11eb-854e-d980983625cc.png)
No way for back to the previous UI also with the parameter uiFlavor to > classic.
What's happen?

**Comment by gorhill** [comment]
> I like the dark mode but not in this way.

It's being worked on, there is no announcement yet that dark mode is supported.

**Comment by gorhill** [comment]
@jeremyperkin You probably noticed I finally brought in [your original changes](https://github.com/gorhill/uBlock/commit/fba5f3d597f86e35b96caf29a73233371fe19852) and added missing CSS variables etc. so hopefully this allows you to further work on this, tell me when you are ready for a pull request to master branch (no need to work on the dark branch, it's too old now). I know there are more CSS variables to create but we can work on this in parallel.

**Comment by happysurf** [comment]
> It's being worked on, there is no announcement yet that dark mode is supported.

Yes, I understand of course, but in the meantime is possible force the old theme?

**Comment by gorhill** [comment]
@happysurf Ok so you are saying that the dark theme is automatically enabled in uBO? If so, I gather your browser is set to dark mode theme?

**Comment by jeremyperkin** [comment]
> @jeremyperkin You probably noticed I finally brought in [your original changes](https://github.com/gorhill/uBlock/commit/fba5f3d597f86e35b96caf29a73233371fe19852) and added missing CSS variables etc. so hopefully this allows you to further work on this, tell me when you are ready for a pull request to master branch (no need to work on the dark branch, it's too old now). I know there are more CSS variables to create but we can work on this in parallel.

Sounds good.   I will take a look later today.  As I am, just waking up on the West Coast.

**Comment by happysurf** [comment]
> 
> 
> @happysurf Ok so you are saying that the dark theme is automatically enabled in uBO? If so, I gather your browser is set to dark mode theme?
Correct, is automatically enabled in uBO, in Firefox I'm using a my dark theme, Ocean Fox:
https://addons.mozilla.org/en-US/firefox/addon/ocean-fox/
In any case also with Mozilla default or light theme the uBO ui remain dark.

**Comment by gorhill** [comment]
I am going to add an advanced setting in next dev build to add ability to force a theme. Once a usable dark theme is well implemented, then I can come up with a way to toggle this in the dashboard.

**Comment by uBlock-user** [comment]
>  If so, I gather your browser is set to dark mode theme?

It stays the same even after dark theme is disabled in Firefox, I guess my OS theme is set to dark too so it's relenting on that.

**Comment by uBlock-user** [comment]
>  If so, I gather your browser is set to dark mode theme?

It stays the same even after dark theme is disabled in Firefox, I guess my OS theme is set to dark too so it's taking that into consideration.

**Comment by gorhill** [comment]
> It stays the same even after dark theme is disabled in Firefox

uBO uses the browser's `prefers-color-scheme` value, so if this value stays to `dark` after disabling the dark theme in the browser, this seems like a browser issue to me -- or it could be by design, I don't know.

**Comment by uBlock-user** [comment]
Still the user should have the choice to disable/enable themes, I may want the dark theme for Firefox but I do not want the dark theme in uBO.

**Comment by happysurf** [comment]
> uBO uses the browser's [`prefers-color-scheme` value](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), so if this value stays to `dark` after disabling the dark theme in the browser, this seems like a browser issue to me -- or it could be by design, I don't know.

My fingerprint parameter is on false (default), the other strings mentioned on the page, are not present in my profile.

**Comment by jeremyperkin** [comment]
Its due to the variant of Firefox you're using.

Create a new profile in Firefox. That should normalize things.  As the
browser is using CSS set by whomever your custom variant of firefox was.
Setting it to a new profile should skip the userChrome settings.

**Comment by happysurf** [comment]
@jeremyperkin Is not a userChrome problem, also with new profile the result is the same.

**Comment by jeremyperkin** [comment]
Just an FYI I am a mod at r/FirefoxCSS.  Have seen this issue multiple
times with users using Firefox variants.

As stated it takes from your OS or can take from Firefox.  Have you tried
installing vanilla firefox and then the extension?

**Comment by happysurf** [comment]
> As stated it takes from your OS or can take from Firefox.  Have you tried
installing vanilla firefox and then the extension?

Yes, no change.

**Comment by happysurf** [comment]
This morning I see on new uBO version, the new parameter _**uiTheme = unset**_, which are the possible variables?

**Comment by gwarser** [comment]
> _**uiTheme = unset**_, which are the possible variables?

https://github.com/gorhill/uBlock/commit/e3a6d8465f19f4ef5d84ceddb9570644cf4fc0a3

**Comment by TheOne320** [comment]
The text in the advanced user options is not readable in dark mode when the line is selected and when cloud saving is activate the top bit of the "my filter" page has a white icon on white background.

**Comment by gwarser** [comment]
Dark theme in the logger in 1.30.9b14 (#1338):

<details>
<summary>Details</summary>

![2020-11-11 07_32_57-Window](https://user-images.githubusercontent.com/4954535/98777262-b1f9e680-23f0-11eb-9238-b2542e18294a.png)

![2020-11-11 07_42_25-uBlock₀ — Protokoll der Netzwerkanfragen](https://user-images.githubusercontent.com/4954535/98777696-81ff1300-23f1-11eb-9fae-86cfb45ab828.png)

</details>

**Comment by krystian3w** [comment]
Also with blind mode all is invnisible.

**Comment by 07416** [comment]
Can you confirm if the dark theme is supposed to work in Firefox for Android (Fenix)? I have the Android 10 dark theme enabled and have made sure that Firefox follows the system scheme, the UBO interface is all white, also after configuring the advanced settings. 

a related issue: https://github.com/mozilla-mobile/fenix/issues/13210

**Comment by PurpleCodingWizard** [comment]
@07416 Its supposed to work in dev builds only as people started to create issues without reading the warning text. 
 https://github.com/uBlockOrigin/uBlock-issues/issues/1389#issuecomment-740127900

**Comment by krystian3w** [comment]
Try test beta addon in Fenix Nightly or maybe in IceRaven: https://github.com/fork-maintainers/iceraven-browser

**Comment by gwarser** [comment]
`click2load.html` support - https://www.reddit.com/r/uBlockOrigin/comments/ld8yf9/is_there_dark_theme_for_the_clicktoload_feature/

**Comment by dreaddr** [comment]
Interested in seeing the extension support switching to Dark/Light theme depending context of the OS theme.

**Comment by hjek** [comment]
How come uBlock Origin remains light when `uiTheme` is set to `dark`?

![ublock_dark](https://user-images.githubusercontent.com/11958965/110172574-9f6f4700-7dfd-11eb-87a3-b995f40af6ab.png)

**Comment by gwarser** [comment]
@hjek https://github.com/uBlockOrigin/uBlock-issues/issues/401#issuecomment-759969330
